name: Deploy to GitHub Pages
on:
  push:
    branches: [ main ]
  workflow_dispatch:
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Build
        run: npm run build
        env:
          VITE_FIREBASE_API_KEY: ${{ secrets.FIREBASE_API_KEY }}
          VITE_FIREBASE_AUTH_DOMAIN: ${{ secrets.FIREBASE_AUTH_DOMAIN }}
          VITE_FIREBASE_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
          VITE_FIREBASE_STORAGE_BUCKET: ${{ secrets.FIREBASE_STORAGE_BUCKET }}
          VITE_FIREBASE_MESSAGING_SENDER_ID: ${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}
          VITE_FIREBASE_APP_ID: ${{ secrets.FIREBASE_APP_ID }}
          VITE_SCRAPING_API_KEY: ${{ secrets.SCRAPING_API_KEY }}
          VITE_SCRAPING_API_URLS: ${{ secrets.SCRAPING_API_URLS }}
      
      - name: Create .nojekyll file
        run: touch docs/.nojekyll
      
      - name: Create 404.html
        run: |
          cat > docs/404.html << 'EOL'
          <!DOCTYPE html>
          <html lang="it">
          <head>
              <meta charset="UTF-8">
              <meta name="viewport" content="width=device-width, initial-scale=1.0">
              <title>Sito momentaneamente non disponibile - TripTaste</title>
              <script>
                  // Reindirizza alla home page dopo un ritardo
                  setTimeout(function() {
                      window.location.href = '/TripTaste/';
                  }, 5000);
                  // Per SPA: salva il percorso corrente
                  sessionStorage.setItem('redirectPath', window.location.pathname);
              </script>
              <style>
                  body {
                      font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
                      background-color: #f5f5dc;
                      display: flex;
                      justify-content: center;
                      align-items: center;
                      height: 100vh;
                      margin: 0;
                  }
                  .container {
                      text-align: center;
                      background-color: white;
                      padding: 30px;
                      border-radius: 10px;
                      box-shadow: 0 5px 15px rgba(0,0,0,0.1);
                      max-width: 500px;
                  }
                  h1 {
                      color: #d35400;
                  }
                  p {
                      margin: 20px 0;
                      line-height: 1.5;
                  }
                  .button {
                      background-color: #d35400;
                      color: white;
                      padding: 10px 20px;
                      border: none;
                      border-radius: 5px;
                      text-decoration: none;
                      display: inline-block;
                      margin-top: 20px;
                  }
              </style>
          </head>
          <body>
              <div class="container">
                  <h1>Sito momentaneamente non disponibile</h1>
                  <p>Ci scusiamo per l'inconveniente, ma il sito è attualmente in manutenzione. Stiamo lavorando per migliorare la tua esperienza.</p>
                  <a href="/TripTaste/" class="button">Torna alla Home</a>
                  <p id="countdown">Sarai reindirizzato automaticamente alla home page tra 5 secondi...</p>
              </div>
              <script>
                  // Conto alla rovescia
                  let seconds = 5;
                  const countdownElement = document.getElementById('countdown');
                  const interval = setInterval(() => {
                      seconds--;
                      if (seconds <= 0) {
                          clearInterval(interval);
                      } else {
                          countdownElement.textContent = `Sarai reindirizzato automaticamente alla home page tra ${seconds} secondi...`;
                      }
                  }, 1000);
              </script>
          </body>
          </html>
          EOL
      
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages
          folder: docs
          clean: true