name: Deploy to GitHub Pages
on:
  push:
    branches: [ main ]
  workflow_dispatch:
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Build
        run: npm run build
        env:
          VITE_FIREBASE_API_KEY: ${{ secrets.FIREBASE_API_KEY }}
          VITE_FIREBASE_AUTH_DOMAIN: ${{ secrets.FIREBASE_AUTH_DOMAIN }}
          VITE_FIREBASE_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
          VITE_FIREBASE_STORAGE_BUCKET: ${{ secrets.FIREBASE_STORAGE_BUCKET }}
          VITE_FIREBASE_MESSAGING_SENDER_ID: ${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}
          VITE_FIREBASE_APP_ID: ${{ secrets.FIREBASE_APP_ID }}
          VITE_SCRAPING_API_KEY: ${{ secrets.SCRAPING_API_KEY }}
          VITE_SCRAPING_API_URLS: ${{ secrets.SCRAPING_API_URLS }}
      
      - name: Create .nojekyll file
        run: touch docs/.nojekyll
      
      - name: Create 404.html
        run: |
          cat > docs/404.html << 'EOL'
          <!DOCTYPE html>
          <html lang="it">
          <head>
              <meta charset="UTF-8">
              <meta name="viewport" content="width=device-width, initial-scale=1.0">
              <title>Reindirizzamento...</title>
              <script>
                // Salva il percorso attuale nel sessionStorage
                sessionStorage.setItem('redirectPath', window.location.pathname);
                
                // Reindirizza alla home page
                window.location.href = '/TripTaste/';
              </script>
          </head>
          <body>
              <p>Reindirizzamento in corso...</p>
          </body>
          </html>
          EOL
      
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages
          folder: docs
          clean: true